### ISSUE TITLE
Unspecified error

### ISSUE THREAD

**Issue by motyc** [FilipMasar/ocr-editor#6]
On the recommendation of @stranak, I tried to use the tool to display our ALTOs created within the https://atrium-research.eu/ project. Unfortunately, the ALTO content will not load and display. The problem may be that the ALTO is for multiple pages, which I don't know how to address within the tool. Would it please be possible to advise or issue a fix if there is any problem on the application side?

I'm attaching the files I'm working with:
[OCR_data.zip](https://github.com/user-attachments/files/16927734/OCR_data.zip)

**Comment by FilipMasar** [comment]
Hey @motyc, happy to see that someone is trying to use this code. 

The problem was indeed that the ALTO file has multiple pages inside it. Unfortunately the code does work only if every page is in a separate file.
What I did to make your example data work
1. split your data into 2 files (each with one page)
2. change the file extension from .alto to .xml (otherwise you can't import it)

Here is the project (folder) which you can directly load into ocr-editor and it should work 
[atrium-project.zip](https://github.com/user-attachments/files/16961803/atrium-project.zip)

**Comment by motyc** [comment]
Dear Filip, thank you for such a swift advice! I can confirm that project works and also that I have been able to reproduce the steps to make it working for our data. We will transform the input data to make imports possible. Thank you again.
